/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guihja;
//
import java.awt.Button;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author YVCX
 */
public class BoardGui extends javax.swing.JPanel {
    private Button[][] board = new Button [13][4];
    private boolean[][] pulsado = new boolean [13][4];
    
    /**
     * Creates new form BoardGui
     */
    public BoardGui() {
        String valor="";
        char c='x';
        
        initComponents();
        this.setLayout (new GridLayout (13,4)); 
         ActionListener ac; 
        for(int i=14; i>=2; i--){
            for(int j=0; j<4;j++){
                valor=LogicaGui.intToChar(i);
                valor+=palo(j);
                
                ac = new ActionListener(){
                  public void actionPerformed(ActionEvent e)
                  {
                    String tecla=e.getActionCommand();
                    pulsado(tecla);
                  }                  

                };
                board[i-2][j]= new Button();
                board[i-2][j].setLabel(valor);
                board[i-2][j].addActionListener(ac);
                this.add(board[i-2][j]);
            }
        }
        this.setVisible(true);
    }
    
    
    private void pulsado(String c) {
      int a = LogicaGui.CharToInt(c.charAt(0));
      char p= c.charAt(1);
      int b= palo(p);
      Carta car = new Carta(a,p);
      if(LogicaGui.pulsadasBoard()<5){
        if(!marcado(a,b)){
            board[a-2][b].setBackground(Color.green);
            LogicaGui.addBoard(car);
        }
        else{
             board[a-2][b].setBackground(new Color(240,240,240));
             LogicaGui.delBoard(car);
        }
      }
      else{
           pulsado[a-2][b]=false;
           board[a-2][b].setBackground(new Color(240,240,240));
           LogicaGui.delBoard(car);
      }
      LogicaGui.procesar();
    }
                    
    private String palo(int j){
        String v="";
        switch(j){
            case 0: v="h";break;
            case 1: v="c";break;            
            case 2: v="d";break;
            case 3: v="s";break;
        }
       return v;
    }
    
     private int palo(char j){
        int v=0;
        switch(j){
            case 'h': v=0;break;
            case 'c': v=1;break;            
            case 'd': v=2;break;
            case 's': v=3;break;
        }
       return v;
    }
     
    private boolean marcado(int a, int b){
        boolean bo=pulsado[a-2][b];
        if(bo){
            pulsado[a-2][b]=false;
        }
        else{
            pulsado[a-2][b]=true;
        }
        return bo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
