/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guihja;

import java.awt.Button;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author YVCX
 */
public class Tablero extends javax.swing.JPanel {

    private Button[][] tableroBot = new Button [13][13];
    private boolean suiters=false;
    private String tecla;
    /**
     * Creates new form Tablero
     */
    public Tablero() {
      
        initComponents();
         this.setLayout (new GridLayout (13,13)); 
         ActionListener ac;          
          LogicaGui.setT(this);
        for(int i=14; i>=2; i--){
            suiters=false;
            for(int j=14; j>=2;j--){
                ac = new ActionListener(){
                  public void actionPerformed(ActionEvent e)
                  {
                    tecla=e.getActionCommand();
                      LogicaGui.pulsacion(tecla);
                    ;}
                  
                };
                
                
                tableroBot[i-2][j-2]= new Button();
                tableroBot[i-2][j-2].setLabel(valorBoton(i,j));
                tableroBot[i-2][j-2].addActionListener(ac);
                this.add(tableroBot[i-2][j-2]);
            }
        }
        this.setVisible(true);
    }
    
    private String valorBoton (int i, int j){
        String valor, a, b;
        int color=2;
            a= LogicaGui.intToChar(i);
            b= LogicaGui.intToChar(j);
            
            if(i>j || i==j) valor= a+b;
            else valor = b+a;
            
            if(i==j){
                suiters=true;
                color=3;
            }
            else if(suiters){
                valor += "s";
                color=4;
            }
            else if(!suiters) valor += "o";
            pintar(i,j,color);
        return valor;
    }
    
    public void pintar(int i, int j, int mode){
        switch(mode){
            case 0: tableroBot[i-2][j-2].setBackground(Color.yellow); break;
            case 1: tableroBot[i-2][j-2].setBackground(new Color(255,102,255)); break; //magenta de porcentaje
            case 2: tableroBot[i-2][j-2].setBackground(new Color(240,240,240)); break; //defult gris
            case 3: tableroBot[i-2][j-2].setBackground(new Color(153,255,153)); break; //verde
            case 4: tableroBot[i-2][j-2].setBackground(new Color(255,153,153)); break; //rojo
            default: tableroBot[i-2][j-2].setBackground(new Color(240,240,240)); break;
        }
    }
    
    public void reset(){
        for(int i=14; i>=2; i--){
            suiters=false;
            for(int j=14; j>=2;j--){
            valorBoton(i,j);
            }
        }
    }
    public int tam(){
        return 13;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(13, 13));
        setMinimumSize(new java.awt.Dimension(13, 13));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
