/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guihja;

import java.awt.Button;
import java.awt.Color;
import java.awt.GridLayout;

/**
 *
 * @author YVCX
 */
public class Tablero extends javax.swing.JPanel {

    private Button[][] tableroBot = new Button [13][13];
    private boolean suiters=false;
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
         this.setLayout (new GridLayout (13,13)); 
         
        for(int i=14; i>=2; i--){
            suiters=false;
            for(int j=14; j>=2;j--){
                tableroBot[i-2][j-2]= new Button(valorBoton(i,j));
                this.add(tableroBot[i-2][j-2]);
            }
        }
        this.setVisible(true);
    }
    
    private String valorBoton (int i, int j){
        String valor, a, b;
            a= LogicaGui.intToChar(i);
            b= LogicaGui.intToChar(j);
            
            if(i>j || i==j) valor= a+b;
            else valor = b+a;
            
            if(i==j)suiters=true;
            else if(suiters)valor += "s";
            else if(!suiters) valor += "o";
        return valor;
    }
    
    public void pintar(int i, int j){
        tableroBot[i-2][j-2].setBackground(Color.yellow);
    }
    
    public int tam(){
        return 13;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(13, 13));
        setMinimumSize(new java.awt.Dimension(13, 13));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
