/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Logica.Carta;
import Logica.Logica;

/**
 *
 * @author YVCX
 */
public class Tablero extends javax.swing.JPanel {
    private Logica log;
    private String dir="/imgs/cards/";
    
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
           jButton1.setVisible(false);
        this.setSize(fondo.getWidth(), fondo.getHeight());
    }
    
    public Tablero(Logica l) {
        initComponents();
        jButton1.setVisible(false);
        log=l;
        this.setSize(fondo.getWidth(), fondo.getHeight());
    }
    
    //poner en logica
    public String cartaPng(Carta c){
        return ""+c.getValor()+c.getColor()+".png";
    }

    private void setJugadores(){
        j11.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j12.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j21.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j22.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j31.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j32.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j41.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j42.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j51.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j52.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j61.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        j62.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
    }
    
    private void setPorcentajes(){
        j1.setText("");
        j2.setText("");
        j3.setText("");
        j4.setText("");
        j5.setText("");
        j6.setText("");
    }
    
    private void setBoard(){
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+"carta.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        j11 = new javax.swing.JLabel();
        j12 = new javax.swing.JLabel();
        j21 = new javax.swing.JLabel();
        j22 = new javax.swing.JLabel();
        j31 = new javax.swing.JLabel();
        j32 = new javax.swing.JLabel();
        j41 = new javax.swing.JLabel();
        j42 = new javax.swing.JLabel();
        j51 = new javax.swing.JLabel();
        j52 = new javax.swing.JLabel();
        j61 = new javax.swing.JLabel();
        j62 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        fase = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(null);

        j1.setText("00.00%");
        add(j1);
        j1.setBounds(250, 130, 50, 20);

        j2.setText("00.00%");
        add(j2);
        j2.setBounds(520, 130, 50, 20);

        j3.setText("00.00%");
        add(j3);
        j3.setBounds(700, 300, 50, 20);

        j4.setText("00.00%");
        add(j4);
        j4.setBounds(510, 470, 50, 20);

        j5.setText("00.00%");
        add(j5);
        j5.setBounds(280, 470, 50, 20);

        j6.setText("00.00%");
        add(j6);
        j6.setBounds(50, 300, 50, 20);

        j11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j11);
        j11.setBounds(250, 20, 70, 100);

        j12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j12);
        j12.setBounds(170, 20, 70, 100);

        j21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j21);
        j21.setBounds(490, 20, 70, 100);

        j22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j22);
        j22.setBounds(570, 20, 70, 100);

        j31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j31);
        j31.setBounds(640, 190, 70, 100);

        j32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j32);
        j32.setBounds(720, 190, 70, 100);

        j41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j41);
        j41.setBounds(480, 510, 70, 100);

        j42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j42);
        j42.setBounds(560, 510, 70, 100);

        j51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j51);
        j51.setBounds(200, 510, 70, 100);

        j52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j52);
        j52.setBounds(280, 510, 70, 100);

        j61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j61);
        j61.setBounds(10, 190, 70, 100);

        j62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        add(j62);
        j62.setBounds(90, 190, 70, 100);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        add(b1);
        b1.setBounds(200, 250, 70, 110);

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        add(b2);
        b2.setBounds(280, 250, 70, 110);

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        add(b3);
        b3.setBounds(360, 250, 70, 110);

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        add(b4);
        b4.setBounds(440, 250, 70, 110);

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        add(b5);
        b5.setBounds(520, 250, 70, 110);

        fase.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        fase.setForeground(new java.awt.Color(255, 255, 255));
        fase.setText("Pre-Flop");
        add(fase);
        fase.setBounds(30, 510, 120, 40);

        jButton1.setText("Cerrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(20, 580, 100, 23);

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(20, 550, 100, 23);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fondo.png"))); // NOI18N
        add(fondo);
        fondo.setBounds(0, 0, 806, 625);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //cerrar
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         log.mirarGanador();
           String s=log.getEstado();
            fase.setText(s);
       if (s=="River"){
           jButton1.setVisible(true);
           jButton2.setVisible(false);
       }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel fase;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j11;
    private javax.swing.JLabel j12;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j21;
    private javax.swing.JLabel j22;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j31;
    private javax.swing.JLabel j32;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j41;
    private javax.swing.JLabel j42;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j51;
    private javax.swing.JLabel j52;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j61;
    private javax.swing.JLabel j62;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
