/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Logica.Carta;
import Logica.Jugador;
import Logica.Logica;
import java.util.ArrayList;

/**
 *
 * @author Grupo 01
 */
public class Tablero  extends javax.swing.JDialog{//extends javax.swing.JPanel {

    private Logica log;
    private String dir="/imgs/cards/";
    //private Jugador[] jugs;
   // private ArrayList<Carta> board = new ArrayList<Carta>();
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        jButton2.setVisible(false);
        this.setSize(fondo.getWidth(), fondo.getHeight());
    }
    
     public Tablero(Logica l) {
        initComponents();
         jButton2.setVisible(false);
        //this.setSize(fondo.getWidth(), fondo.getHeight());
        this.setSize(810, 650);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("HJA: PRACTICA3 - TABLERO - GRUPO 01");
        log = l;
        setJugadores();   
        setPorcentajes(log.mirarGanador());
    }
    
    private String cartaPng(Carta c){
        return ""+c.getValor()+c.getColor()+".png";
    }

    private void setJugadores(){
        String d;
        Jugador[] jugs=log.getJugadores();
        
        d=cartaPng(jugs[0].getCarta(1));
        j11.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[0].getCarta(0));
        j12.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[1].getCarta(1));
        j21.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[1].getCarta(0));
        j22.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[2].getCarta(1));
        j31.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[2].getCarta(0));
        j32.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[3].getCarta(1));
        j41.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[3].getCarta(0));
        j42.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[4].getCarta(1));
        j51.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[4].getCarta(0));
        j52.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[5].getCarta(1));
        j61.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        d=cartaPng(jugs[5].getCarta(0));
        j62.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
    }
    
    private void setPorcentajes(double[] por){
        j1.setText(""+por[0]+" %");
        j2.setText(""+por[1]+" %");
        j3.setText(""+por[2]+" %");
        j4.setText(""+por[3]+" %");
        j5.setText(""+por[4]+" %");
        j6.setText(""+por[5]+" %");
    }
    
    private void setBoard(){
        ArrayList<Carta> b=log.getBoard();
        String d;
        if(log.getEstado()=="Flop"){
            d=cartaPng(b.get(0));
            b1.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
            d=cartaPng(b.get(1));
            b2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
            d=cartaPng(b.get(2));
            b3.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        }
        else if(log.getEstado()=="Turn"){
            d=cartaPng(b.get(3));
            b4.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        }
        else {
            d=cartaPng(b.get(4));
            b5.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir+d)));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        j11 = new javax.swing.JLabel();
        j12 = new javax.swing.JLabel();
        j21 = new javax.swing.JLabel();
        j22 = new javax.swing.JLabel();
        j31 = new javax.swing.JLabel();
        j32 = new javax.swing.JLabel();
        j41 = new javax.swing.JLabel();
        j42 = new javax.swing.JLabel();
        j51 = new javax.swing.JLabel();
        j52 = new javax.swing.JLabel();
        j61 = new javax.swing.JLabel();
        j62 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        fase = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        j1.setText("00.00%");
        getContentPane().add(j1);
        j1.setBounds(260, 140, 50, 10);

        j2.setText("00.00%");
        getContentPane().add(j2);
        j2.setBounds(530, 140, 50, 10);

        j3.setText("00.00%");
        getContentPane().add(j3);
        j3.setBounds(720, 310, 50, 10);

        j4.setText("00.00%");
        getContentPane().add(j4);
        j4.setBounds(510, 476, 50, 14);

        j5.setText("00.00%");
        getContentPane().add(j5);
        j5.setBounds(280, 480, 50, 10);

        j6.setText("00.00%");
        getContentPane().add(j6);
        j6.setBounds(60, 310, 50, 10);

        j11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j11);
        j11.setBounds(250, 20, 70, 100);

        j12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j12);
        j12.setBounds(170, 20, 70, 100);

        j21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j21);
        j21.setBounds(490, 20, 70, 100);

        j22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j22);
        j22.setBounds(570, 20, 70, 100);

        j31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j31);
        j31.setBounds(640, 190, 70, 100);

        j32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j32);
        j32.setBounds(720, 190, 70, 100);

        j41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j41);
        j41.setBounds(480, 510, 70, 100);

        j42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j42);
        j42.setBounds(560, 510, 70, 100);

        j51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j51);
        j51.setBounds(200, 510, 70, 100);

        j52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j52);
        j52.setBounds(280, 510, 70, 100);

        j61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j61);
        j61.setBounds(10, 190, 70, 100);

        j62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/10c.png"))); // NOI18N
        getContentPane().add(j62);
        j62.setBounds(90, 190, 70, 100);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        getContentPane().add(b1);
        b1.setBounds(200, 250, 70, 110);

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        getContentPane().add(b2);
        b2.setBounds(280, 250, 70, 110);

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        getContentPane().add(b3);
        b3.setBounds(360, 250, 70, 110);

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        getContentPane().add(b4);
        b4.setBounds(440, 250, 70, 110);

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cards/down.png"))); // NOI18N
        getContentPane().add(b5);
        b5.setBounds(520, 250, 70, 110);

        fase.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        fase.setForeground(new java.awt.Color(255, 255, 255));
        fase.setText("Pre-Flop");
        getContentPane().add(fase);
        fase.setBounds(30, 510, 120, 40);

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 550, 100, 23);

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 580, 100, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("J1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 130, 20, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("J2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 130, 20, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("J3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 300, 20, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("J4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 470, 20, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("J5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 470, 20, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("J6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 300, 20, 17);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fondo.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 806, 625);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s=log.getEstado();
        setBoard(); 
        setPorcentajes(log.mirarGanador());
        fase.setText(s);
        s=log.getEstado();
        
       if (s=="Fin"){
           jButton1.setVisible(false);
           jButton2.setVisible(true);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // cerrar pantalla
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel fase;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j11;
    private javax.swing.JLabel j12;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j21;
    private javax.swing.JLabel j22;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j31;
    private javax.swing.JLabel j32;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j41;
    private javax.swing.JLabel j42;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j51;
    private javax.swing.JLabel j52;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j61;
    private javax.swing.JLabel j62;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
