
package Gui;

import Logica.Logica;
import javax.swing.JCheckBox;
import javax.swing.JLabel;


/**
 *
 * @author Grupo 01
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    private JLabel j[];
    private JCheckBox r[];
    private Logica logica;
   
    public Inicio() {
        initComponents();
        j= new JLabel[]{j1,j2,j3,j4};
        r= new JCheckBox[]{r1,r2,r3,r4};
    }
    
    public Inicio(Logica l){
        logica=l;
        initComponents();
        j= new JLabel[]{j1,j2,j3,j4};
        r= new JCheckBox[]{r1,r2,r3,r4};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        r1 = new javax.swing.JCheckBox();
        r2 = new javax.swing.JCheckBox();
        r3 = new javax.swing.JCheckBox();
        r4 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Jugadores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 14, -1, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 200, -1));

        j1.setText("Jugador 1");
        add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        j2.setText("Jugador 2");
        add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        j3.setText("Jugador 3");
        add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        j4.setText("Jugador 4");
        add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, -1));

        jButton8.setBackground(new java.awt.Color(0, 204, 51));
        jButton8.setText("Jugar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 80, 20));

        jButton10.setBackground(new java.awt.Color(255, 51, 51));
        jButton10.setText("Reset");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, 20));

        r1.setText("Jugador Automatico");
        add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 20));

        r2.setText("Jugador Automatico");
        add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));

        r3.setText("Jugador Automatico");
        add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 20));

        r4.setText("Jugador Automatico");
        add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

  
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      
    }//GEN-LAST:event_jButton10ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        for(int i=0; i<4; i++){
            if(r[i].isSelected()){
               logica.addJugadorAutomatico();
               logica.marcarBot(i);
            }
            else logica.addJugador();
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void enable(int num){
        int i;
        for(i=0;i<num;i++){
            j[i].setEnabled(true);
            r[i].setEnabled(true);
        }
        for(i=num;i<6;i++){
            j[i].setEnabled(false);
            r[i].setEnabled(false);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JCheckBox r1;
    private javax.swing.JCheckBox r2;
    private javax.swing.JCheckBox r3;
    private javax.swing.JCheckBox r4;
    // End of variables declaration//GEN-END:variables
}
